// ...existing code...
Scaffold(
  // ...existing code...
  body: Column(
    // ...existing code...
    children: [
      // ...existing code...
      ElevatedButton(
        onPressed: () {
          Navigator.pushNamed(context, '/tripAdvice');
        },
        child: const Text('Trip Advice'),
      ),
      // ...existing code...
    ],
  ),
  // ...existing code...
)
// ...existing code...

